[Config Sweep]
network = omnet_tictoc.Tictoc1
sim-time-limit = 2s
**.linkDelay = ${10ms,100ms,500ms}

[Config C1]
network = omnet_tictoc.Network
sim-time-limit = 10s
# ARP vereinfachen
*.host*.ipv4.arp.typename = "GlobalArp"
# Feste Positionen (100m Abstand)
*.hostA.mobility.typename = "StationaryMobility"
*.hostB.mobility.typename = "StationaryMobility"
*.hostA.mobility.initialX = 0m
*.hostA.mobility.initialY = 0m
*.hostB.mobility.initialX = 100m
*.hostB.mobility.initialY = 0m
# Funkreichweite (größer als Distanz → Kommunikation funktioniert)
*.host*.wlan[0].radio.transmitter.communicationRange = 200m
*.host*.wlan[0].radio.receiver.ignoreInterference = true
# IEEE 802.11 im Ad-Hoc-Modus betreiben
*.host*.wlan[0].mgmt.typename = "Ieee80211MgmtAdhoc"
*.host*.wlan[0].agent.typename = ""
# UDP Sender
*.hostA.numApps = 1
*.hostA.app[0].typename = "UdpBasicApp"
*.hostA.app[0].destAddresses = "hostB"
*.hostA.app[0].destPort = 5000
*.hostA.app[0].messageLength = 200B
*.hostA.app[0].sendInterval = 50ms
# UDP Empfänger
*.hostB.numApps = 1
*.hostB.app[0].typename = "UdpSink"
*.hostB.app[0].localPort = 5000
*.configurator.assignAddresses = true
*.configurator.addStaticRoutes = false

[Config C2]
extends = C1
# Sendeintervall vergrößern (geringere Sendefrequenz)
*.hostA.app[0].sendInterval = 200ms

[Config C3]
extends = C1
# Effektive Reichweite reduzieren: Sendeleistung stark senken
*.hostA.wlan[0].radio.transmitter.power = 1nW